### ISSUE TITLE
关于启动问题

### ISSUE THREAD

**Issue by 2252664145** [LomotHo/minecraft-bedrock#13]
我找到了服务器插件，但是他是用
LD_LIBRARY_PATH=. LD_PRELOAD=./mods/a.so ./bedrock_server
来启动服务器的，请问在你这个容器里面应该怎么启动它？

**Comment by LomotHo** [comment]
建议使用标签base镜像，然后添加环境变量 -e LD_PRELOAD=./mods/a.so
例如这样：
```sh
docker run -itd --restart=always --name=mcpe --net=host \
  -v /opt/mcpe-data:/mcpe \
  -e LD_PRELOAD=./mods/a.so \
  lomot/minecraft-bedrock:base
```
这样的话/opt/mcpe-data文件夹将由你自己来管理，服务器升级的时候需要自己去下载服务端文件
这里有对base镜像的说明： https://github.com/LomotHo/minecraft-bedrock/blob/master/readme_zh.md#%E5%85%B3%E4%BA%8E%E8%A1%8C%E4%B8%BA%E5%8C%85%E8%B5%84%E6%BA%90%E5%8C%85%E6%8F%92%E4%BB%B6

**Comment by 2252664145** [comment]
好的，谢谢
