### ISSUE TITLE
Server will not start correctly, get error message

### ISSUE THREAD

**Issue by langph** [LomotHo/minecraft-bedrock#21]
After upgrading (with watchtower) the server will not start. 

I get this message:

/mcpe/script/docker-entrypoint.sh: 25: exec: bedrock_server: not found

I think it is looking for the server in the wrong path.

**Comment by LomotHo** [comment]
try to delete the image and pull it again.

**Comment by LomotHo** [comment]
```sh
docker image rm lomot/minecraft-bedrock:1.16.1.02
docker pull lomot/minecraft-bedrock:1.16.1.02
```
