### ISSUE TITLE
Please update to version 1.16.201.03

### ISSUE THREAD

**Issue by ddecaro** [LomotHo/minecraft-bedrock#27]
Hi There,

How long do you prefer to wait on doing a new build after  a new release? 1.16.201.03 was released in the last couple of days to fix a crashing issue reported in the below link. 

https://bugs.mojang.com/browse/BDS-10666

Thanks for your time.

**Comment by LomotHo** [comment]
now the update is ok

**Comment by ddecaro** [comment]
Thanks for the quick update. It has fixed the crashing I was experiencing.
