### ISSUE TITLE
version `GLIBCXX_xxx' not found 

### ISSUE THREAD

**Issue by Coldsay** [LomotHo/minecraft-bedrock#37]
Hello, 

After update to latest image today, I have the following errors when starting the container: 

 | stdout | /mcpe/server/bedrock_server: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_2.30' not found (required by /mcpe/server/bedrock_server)

 | stdout | /mcpe/server/bedrock_server: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /mcpe/server/bedrock_server)

 | stdout | /mcpe/server/bedrock_server: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /mcpe/server/bedrock_server)

Running on Synology, no problems before this update

**Comment by ddribin** [comment]
I see the same thing on an Ubuntu 22.04 server. It works if I build a custom image from `ubuntu:22.04` instead of `debian:10-slim`:

```
diff --git a/Dockerfile b/Dockerfile
index ac5e2af..535496c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -27,7 +27,8 @@ COPY ./script $SCRIPT_PATH
 
 ##################  for relaese  #########################
 # FROM ubuntu:18.04 as production
-FROM debian:10-slim as production
+# FROM debian:10-slim as production
+FROM ubuntu:22.04 as production
 
 # install packages & config docker
 RUN apt-get update && \
```

**Comment by LomotHo** [comment]
i will fix this soon

**Comment by LomotHo** [comment]
problem solved 🥳

**Comment by Coldsay** [comment]
Working perfectly now! Thanks a lot for fast correction, and globally for all your work :)

NB : don't forget to move the "latest" tag to this version !

Regards,
