### ISSUE TITLE
如何开启坐标显示

### ISSUE THREAD

**Issue by Landy908** [LomotHo/minecraft-bedrock#4]
求问，领域服可以导入单机已开启坐标显示的地图，那么该专业服如何导入呢？
或者有别的什么办法开启坐标显示呢？

**Comment by LomotHo** [comment]
其实游戏控制台有一个显示坐标的命令，你在命令行输入```docker attach mcpe```可以进入控制台，然后再控制台中输入```gamerule showcoordinates true```就可以开启坐标显示了。
