### ISSUE TITLE
如何查看日志

### ISSUE THREAD

**Issue by 2252664145** [LomotHo/minecraft-bedrock#5]
在原版启动控制台能显示玩家什么时候登陆，什么时候退出，在你项目里打开控制台是不会显示之前的记录，请问如何才能看到？

**Comment by LomotHo** [comment]
使用命令 docker logs mcpe 即可查看日志

**Comment by 2252664145** [comment]
好的，感谢

**Comment by 2252664145** [comment]
请问能不能添加可以记录游戏里聊天信息的功能？

**Comment by LomotHo** [comment]
> 请问能不能添加可以记录游戏里聊天信息的功能？

这个应该是插件方面做的事，我暂时没有去参与的打算
