### ISSUE TITLE
docker attach mcpe seems to not do anything

### ISSUE THREAD

**Issue by pellcorp** [LomotHo/minecraft-bedrock#7]
I am running the latest image on ubuntu and docker attach mcpe never gives me a server prompt, is it supposed to?

**Comment by pellcorp** [comment]
ah never mind, I misunderstood

**Comment by pellcorp** [comment]
It actually works fine locally, but if I ssh into a cloud server and try to do attach I never get a response from the server.  Must be something weird about my config.

**Comment by LomotHo** [comment]
> It actually works fine locally, but if I ssh into a cloud server and try to do attach I never get a response from the server. Must be something weird about my config.

can you show me your logs and the command you typed？
use ```docker logs mcpe``` to print the logs

**Comment by pellcorp** [comment]
Ah, so I had forgot to add -ti to the run command remotely, soon as I did that all was fine :-(

https://stackoverflow.com/questions/25267372/correct-way-to-detach-from-a-container-without-stopping-it/45985809#45985809

**Comment by pellcorp** [comment]
by the way love your docker image, thanks so much for your efforts.  I fire up minecraft for my kids and their friends to play on a vultr instance.

**Comment by pellcorp** [comment]
apologies for wasting your time

**Comment by LomotHo** [comment]
Very glad to help you!
